image: "gcc"

before_script:
  - make

project1:
  script:
    - cd Projeto1/student-tests && ./all.sh ../proj1
    - cd ../testes-relatorio && ./all.sh ../proj1

project2:
  script:
    - cd Projeto2/tests && ./all.sh ../proj2
    - cd ../testes-relatorio && ./all.sh ../proj2
